server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          # 认证服务器的地址
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/oauth2/jwks